from Multiclass_code import tsfresh_multiclass_dataPreprocessing
from Multiclass_code import tsfresh_multiclass_calcFeatures
from Multiclass_code import tsfresh_multiclass_selectFeatures
from Multiclass_code import tsfresh_multiclass_normal_classify
from Multiclass_code import tsfresh_multiclass_classification
from Multiclass_code import tsfresh_multiclass_learningCurve

tsfresh_multiclass_dataPreprocessing.start()
tsfresh_multiclass_calcFeatures.start()
tsfresh_multiclass_selectFeatures.start()
tsfresh_multiclass_normal_classify.start()
tsfresh_multiclass_classification.start()
tsfresh_multiclass_learningCurve.start()

